import { Sora } from "next/font/google";
import "./globals.css";
import Header from "./_components/Header";
import Footer from "./_components/Footer";
import Sidebar from "./_components/Sidebar";
const sora = Sora({
  subsets: ["latin"],
  weights: ["300", "400", "500", "600", "700"],
});
export const metadata = {
  title: "Movie Rental",
  description: "Generated by Movie Rental",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="dark root">
      <body
        className={`${sora.className}  dark:bg-body bg-white font-[Sora] dark:text-white text-dark`}
      >
        {children}
      </body>
    </html>
  );
}
