const booksData = [
    {
        "id": 1,
        "name": "JavaScript and Jquery",
        "author": "Jon Duckett",
        "thumbnail": "https://i.ibb.co/v34VLSV/js-jquery.png",
        "price": 62,
        "rating": 4,
        "favourite": false,
        "publishedYear": 2014,
    },
    {
        "id": 2,
        "name": "Eloquent JavaScript",
        "author": "Marijn Haverbeke",
        "thumbnail": "https://i.ibb.co/x7BdSGc/eloquent-js.jpg",
        "price": 49,
        "rating": 5,
        "favourite": true,
        "publishedYear": 2018,
    },
    {
        "id": 3,
        "name": "JavaScript Definitive Guide",
        "author": "David Flanagan",
        "thumbnail": "https://i.ibb.co/D9CKx9H/the-js-definitive-guide.jpg",
        "price": 30,
        "rating": 5,
        "favourite": false,
        "publishedYear": 2011,
    },
    {
        "id": 4,
        "name": "JavaScript The Good Parts",
        "author": "Douglas Crockford",
        "thumbnail": "https://i.ibb.co/bLn4fy2/js-the-good-parts.jpg",
        "price": 35,
        "rating": 3,
        "favourite": true,
        "publishedYear": 2008,
    },
    {
        "id": 5,
        "name": "JavaScript Design Patterns",
        "author": "Addy Osmani",
        "thumbnail": "https://i.ibb.co/0Jp3pk5/learning-js-design-patterns.jpg",
        "price": 40,
        "rating": 4,
        "favourite": false,
        "publishedYear": 2015,
    },
    {
        "id": 6,
        "name": "Learn JavaScript Quickly",
        "author": "Code Quickly",
        "thumbnail": "https://i.ibb.co/Gv8tcH5/learn-js-quicky.jpg",
        "price": 46,
        "rating": 3,
        "favourite": true,
        "publishedYear": 2019,
    },
    {
        "id": 7,
        "name": "The Road To React",
        "author": "Robin Wieruch",
        "thumbnail": "https://i.ibb.co/K5KNDRy/the-road-to-react.jpg",
        "price": 46,
        "rating": 4,
        "favourite": false,
        "publishedYear": 2016,
    },
    {
        "id": 8,
        "name": "React Key Concept",
        "author": "Maximilian Schwarzmuller",
        "thumbnail": "https://i.ibb.co/L5JkZfT/react-key-concept.jpg",
        "price": 46,
        "rating": 4,
        "favourite": true,
        "publishedYear": 2020,
    }
]

export default booksData;